Exécute l'un après l'autre les exercices suivants, en expliquant en détail comme pour un débutant chacune des étapes exécutées : GenAI & Machine Learning Bootcamp 2025 - Full Time 2025 - PSTB Application for Data Analysis Intro to Numpy Exercises XP 
Exercises XP
Last Updated: March 7th, 2025

What You Will Learn:
Core NumPy operations including array creation, manipulation, and basic array operations.
Skills in handling one-dimensional and multi-dimensional arrays.


What You Will Create:
A series of NumPy arrays demonstrating different operations, ranging from simple array creation to more complex manipulations.


🌟 Exercise 1 : Array Creation and Manipulation
Instructions
Create a 1D NumPy array containing numbers from 0 to 9.

Expected Output: 
array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


🌟 Exercise 2 : Type Conversion and Array Operations
Instructions
Convert a list [3.14, 2.17, 0, 1, 2] into a NumPy array and convert its data type to integer.

Expected Output:
array([3, 2, 0, 1, 2])


🌟 Exercise 3 : Working with Multi-Dimensional Arrays
Instructions
Create a 3x3 NumPy array with values ranging from 1 to 9.

Expected Output:
array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])


🌟 Exercise 4 : Creating Multi-Dimensional Array with Random Numbers
Instructions
Create a 2D NumPy array of shape (4, 5) filled with random numbers.

Expected Output:
array([[0.56, 0.85, 0.01, 0.42, 0.68],
       [0.22, 0.37, 0.73, 0.93, 0.39],
       [0.44, 0.03, 0.87, 0.02, 0.83],
       [0.78, 0.87, 0.98, 0.80, 0.46]])


🌟 Exercise 5 : Indexing Arrays
Instructions
Select the second row from a given 2D NumPy array.

Expected Output:
array = np.array([[21,22,23,22,22],[20, 21, 22, 23, 24],[21,22,23,22,22]])


🌟 Exercise 6 : Reversing elements
Instructions
Reverse the order of elements in a given 1D NumPy array (first element becomes last).

Expected Output:
array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])


🌟 Exercise 7 : Identity Matrix
Instructions
Create a 4x4 identity matrix using NumPy.

Expected Output:
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])


🌟 Exercise 8 : Simple Aggregate Funcs
Instructions
Find the sum and average of a given 1D array.

Expected Output:
Sum: 45, Average: 4.5


🌟 Exercise 9 : Create Array and Change its Structure
Instructions
Create a NumPy array with elements from 1 to 20; then reshape it into a 4x5 matrix.

Expected Output:
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])


🌟 Exercise 10 : Conditional Selection of Values
Instructions
Extract all odd numbers from a given NumPy array.

Expected Output:
array([1, 3, 5, 7, 9])


ChatGPT a dit :

Copier
import numpy as np

# 🌟 Exercise 1: Array Creation and Manipulation
exercise_1 = np.arange(10)  # Create an array from 0 to 9

# 🌟 Exercise 2: Type Conversion and Array Operations
exercise_2 = np.array([3.14, 2.17, 0, 1, 2], dtype=int)

# 🌟 Exercise 3: Working with Multi-Dimensional Arrays
exercise_3 = np.arange(1, 10).reshape(3, 3)

# 🌟 Exercise 4: Creating Multi-Dimensional Array with Random Numbers
np.random.seed(0)  # For reproducibility
exercise_4 = np.round(np.random.rand(4, 5), 2)

# 🌟 Exercise 5: Indexing Arrays
array_5 = np.array([[21, 22, 23, 22, 22],
                    [20, 21, 22, 23, 24],
                    [21, 22, 23, 22, 22]])
exercise_5 = array_5[1]  # Second row

# 🌟 Exercise 6: Reversing elements
exercise_6 = np.arange(10)[::-1]

# 🌟 Exercise 7: Identity Matrix
exercise_7 = np.eye(4)

# 🌟 Exercise 8: Simple Aggregate Funcs
array_8 = np.arange(10)
sum_8 = np.sum(array_8)
avg_8 = np.mean(array_8)

# 🌟 Exercise 9: Create Array and Change its Structure
exercise_9 = np.arange(1, 21).reshape(4, 5)

# 🌟 Exercise 10: Conditional Selection of Values
array_10 = np.arange(10)
exercise_10 = array_10[array_10 % 2 == 1]

(
    exercise_1, exercise_2, exercise_3, exercise_4, exercise_5,
    exercise_6, exercise_7, (sum_8, avg_8), exercise_9, exercise_10
)


# Re-execute the exercises with detailed explanations in Python.

import numpy as np

# 🌟 Exercise 1: Array Creation and Manipulation
# Create a 1D array from 0 to 9
exercise_1 = np.arange(10)

# 🌟 Exercise 2: Type Conversion and Array Operations
# Convert list to array and cast to integers
exercise_2 = np.array([3.14, 2.17, 0, 1, 2], dtype=int)

# 🌟 Exercise 3: Working with Multi-Dimensional Arrays
# Create a 3x3 array with values 1 to 9
exercise_3 = np.arange(1, 10).reshape(3, 3)

# 🌟 Exercise 4: Creating Multi-Dimensional Array with Random Numbers
# Create a 4x5 array with random numbers between 0 and 1
np.random.seed(0)
exercise_4 = np.round(np.random.rand(4, 5), 2)

# 🌟 Exercise 5: Indexing Arrays
# Select second row from given array
array_5 = np.array([[21, 22, 23, 22, 22],
                    [20, 21, 22, 23, 24],
                    [21, 22, 23, 22, 22]])
exercise_5 = array_5[1]

# 🌟 Exercise 6: Reversing elements
# Reverse elements of an array
exercise_6 = np.arange(10)[::-1]

# 🌟 Exercise 7: Identity Matrix
# Create a 4x4 identity matrix
exercise_7 = np.eye(4)

# 🌟 Exercise 8: Simple Aggregate Funcs
# Sum and average of a 1D array
array_8 = np.arange(10)
sum_8 = np.sum(array_8)
avg_8 = np.mean(array_8)

# 🌟 Exercise 9: Create Array and Change its Structure
# Create an array 1-20 and reshape to 4x5
exercise_9 = np.arange(1, 21).reshape(4, 5)

# 🌟 Exercise 10: Conditional Selection of Values
# Extract all odd numbers
array_10 = np.arange(10)
exercise_10 = array_10[array_10 % 2 == 1]

exercise_1, exercise_2, exercise_3, exercise_4, exercise_5, exercise_6, exercise_7, (sum_8, avg_8), exercise_9, exercise_10
Voici les explications détaillées de chaque exercice avec le code correspondant :

🌟 Exercice 1 : Création d’un tableau
python
Copier
Modifier
import numpy as np
arr = np.arange(10)
Explication : np.arange(10) génère un tableau contenant les entiers de 0 à 9.

🌟 Exercice 2 : Conversion de types
python
Copier
Modifier
arr = np.array([3.14, 2.17, 0, 1, 2], dtype=int)
Explication : On convertit une liste de décimaux en tableau NumPy et on force le type int.

🌟 Exercice 3 : Tableau 3x3
python
Copier
Modifier
arr = np.arange(1, 10).reshape(3, 3)
Explication : On génère les nombres de 1 à 9, puis on les réorganise en matrice 3x3.

🌟 Exercice 4 : Tableau aléatoire 4x5
python
Copier
Modifier
np.random.seed(0)
arr = np.round(np.random.rand(4, 5), 2)
Explication : Création d’un tableau 4x5 rempli de valeurs aléatoires entre 0 et 1, arrondies à deux décimales.

🌟 Exercice 5 : Indexation
python
Copier
Modifier
arr = np.array([[21, 22, 23, 22, 22],
                [20, 21, 22, 23, 24],
                [21, 22, 23, 22, 22]])
second_row = arr[1]
Explication : On sélectionne la 2e ligne (index 1) du tableau 2D.

🌟 Exercice 6 : Inversion
python
Copier
Modifier
arr = np.arange(10)[::-1]
Explication : On inverse l’ordre du tableau avec une tranchée négative ([::-1]).

🌟 Exercice 7 : Matrice identité
python
Copier
Modifier
arr = np.eye(4)
Explication : Création d'une matrice identité 4x4.

🌟 Exercice 8 : Somme et Moyenne
python
Copier
Modifier
arr = np.arange(10)
s = np.sum(arr)
m = np.mean(arr)
Explication : np.sum calcule la somme, np.mean la moyenne.

🌟 Exercice 9 : Reshape
python
Copier
Modifier
arr = np.arange(1, 21).reshape(4, 5)
Explication : Création d’un tableau de 1 à 20 et remodelage en matrice 4x5.

🌟 Exercice 10 : Sélection conditionnelle
python
Copier
Modifier
arr = np.arange(10)
odd_numbers = arr[arr % 2 == 1]
Explication : On filtre les valeurs impaires avec une condition.

Souhaites-tu que je réaffiche le résultat de chaque opération ?

In [ ]:

# 🌟 Exercise 1: Array Creation and Manipulation
exercise_1 = np.arange(10)  # Create an array from 0 to 9

# 🌟 Exercise 2: Type Conversion and Array Operations
exercise_2 = np.array([3.14, 2.17, 0, 1, 2], dtype=int)

# 🌟 Exercise 3: Working with Multi-Dimensional Arrays
exercise_3 = np.arange(1, 10).reshape(3, 3)

# 🌟 Exercise 4: Creating Multi-Dimensional Array with Random Numbers
np.random.seed(0)  # For reproducibility
exercise_4 = np.round(np.random.rand(4, 5), 2)

# 🌟 Exercise 5: Indexing Arrays
array_5 = np.array([[21, 22, 23, 22, 22],
                    [20, 21, 22, 23, 24],
                    [21, 22, 23, 22, 22]])
exercise_5 = array_5[1]  # Second row

# 🌟 Exercise 6: Reversing elements
exercise_6 = np.arange(10)[::-1]

# 🌟 Exercise 7: Identity Matrix
exercise_7 = np.eye(4)

# 🌟 Exercise 8: Simple Aggregate Funcs
array_8 = np.arange(10)
sum_8 = np.sum(array_8)
avg_8 = np.mean(array_8)

# 🌟 Exercise 9: Create Array and Change its Structure
exercise_9 = np.arange(1, 21).reshape(4, 5)

# 🌟 Exercise 10: Conditional Selection of Values
array_10 = np.arange(10)
exercise_10 = array_10[array_10 % 2 == 1]

(
    exercise_1, exercise_2, exercise_3, exercise_4, exercise_5,
    exercise_6, exercise_7, (sum_8, avg_8), exercise_9, exercise_10
)


# Re-execute the exercises with detailed explanations in Python.

import numpy as np

# 🌟 Exercise 1: Array Creation and Manipulation
# Create a 1D array from 0 to 9
exercise_1 = np.arange(10)

# 🌟 Exercise 2: Type Conversion and Array Operations
# Convert list to array and cast to integers
exercise_2 = np.array([3.14, 2.17, 0, 1, 2], dtype=int)

# 🌟 Exercise 3: Working with Multi-Dimensional Arrays
# Create a 3x3 array with values 1 to 9
exercise_3 = np.arange(1, 10).reshape(3, 3)

# 🌟 Exercise 4: Creating Multi-Dimensional Array with Random Numbers
# Create a 4x5 array with random numbers between 0 and 1
np.random.seed(0)
exercise_4 = np.round(np.random.rand(4, 5), 2)

# 🌟 Exercise 5: Indexing Arrays
# Select second row from given array
array_5 = np.array([[21, 22, 23, 22, 22],
                    [20, 21, 22, 23, 24],
                    [21, 22, 23, 22, 22]])
exercise_5 = array_5[1]

# 🌟 Exercise 6: Reversing elements
# Reverse elements of an array
exercise_6 = np.arange(10)[::-1]

# 🌟 Exercise 7: Identity Matrix
# Create a 4x4 identity matrix
exercise_7 = np.eye(4)

# 🌟 Exercise 8: Simple Aggregate Funcs
# Sum and average of a 1D array
array_8 = np.arange(10)
sum_8 = np.sum(array_8)
avg_8 = np.mean(array_8)

# 🌟 Exercise 9: Create Array and Change its Structure
# Create an array 1-20 and reshape to 4x5
exercise_9 = np.arange(1, 21).reshape(4, 5)

# 🌟 Exercise 10: Conditional Selection of Values
# Extract all odd numbers
array_10 = np.arange(10)
exercise_10 = array_10[array_10 % 2 == 1]

exercise_1, exercise_2, exercise_3, exercise_4, exercise_5, exercise_6, exercise_7, (sum_8, avg_8), exercise_9, exercise_10
Voici les explications détaillées de chaque exercice avec le code correspondant :

🌟 Exercice 1 : Création d’un tableau
python
Copier
Modifier
import numpy as np
arr = np.arange(10)
Explication : np.arange(10) génère un tableau contenant les entiers de 0 à 9.

🌟 Exercice 2 : Conversion de types
python
Copier
Modifier
arr = np.array([3.14, 2.17, 0, 1, 2], dtype=int)
Explication : On convertit une liste de décimaux en tableau NumPy et on force le type int.

🌟 Exercice 3 : Tableau 3x3
python
Copier
Modifier
arr = np.arange(1, 10).reshape(3, 3)
Explication : On génère les nombres de 1 à 9, puis on les réorganise en matrice 3x3.

🌟 Exercice 4 : Tableau aléatoire 4x5
python
Copier
Modifier
np.random.seed(0)
arr = np.round(np.random.rand(4, 5), 2)
Explication : Création d’un tableau 4x5 rempli de valeurs aléatoires entre 0 et 1, arrondies à deux décimales.

🌟 Exercice 5 : Indexation
python
Copier
Modifier
arr = np.array([[21, 22, 23, 22, 22],
                [20, 21, 22, 23, 24],
                [21, 22, 23, 22, 22]])
second_row = arr[1]
Explication : On sélectionne la 2e ligne (index 1) du tableau 2D.

🌟 Exercice 6 : Inversion
python
Copier
Modifier
arr = np.arange(10)[::-1]
Explication : On inverse l’ordre du tableau avec une tranchée négative ([::-1]).

🌟 Exercice 7 : Matrice identité
python
Copier
Modifier
arr = np.eye(4)
Explication : Création d'une matrice identité 4x4.

🌟 Exercice 8 : Somme et Moyenne
python
Copier
Modifier
arr = np.arange(10)
s = np.sum(arr)
m = np.mean(arr)
Explication : np.sum calcule la somme, np.mean la moyenne.

🌟 Exercice 9 : Reshape
python
Copier
Modifier
arr = np.arange(1, 21).reshape(4, 5)
Explication : Création d’un tableau de 1 à 20 et remodelage en matrice 4x5.

🌟 Exercice 10 : Sélection conditionnelle
python
Copier
Modifier
arr = np.arange(10)
odd_numbers = arr[arr % 2 == 1]
Explication : On filtre les valeurs impaires avec une condition.

Souhaites-tu que je réaffiche le résultat de chaque opération ?








